
MG_delphes_atlas=[
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_01/delphised_atlas.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_02/delphised_atlas.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_03/delphised_atlas.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_04/delphised_atlas.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_05/delphised_atlas.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_06/delphised_atlas.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_07/delphised_atlas.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_08/delphised_atlas.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_09/delphised_atlas.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_10/delphised_atlas.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_11/delphised_atlas.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_12/delphised_atlas.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_13/delphised_atlas.root',
]
MG_delphes_cms=[
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_01/delphised_cms.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_02/delphised_cms.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_03/delphised_cms.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_04/delphised_cms.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_05/delphised_cms.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_06/delphised_cms.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_07/delphised_cms.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_08/delphised_cms.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_09/delphised_cms.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_10/delphised_cms.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_11/delphised_cms.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_12/delphised_cms.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_13/delphised_cms.root',
]
MG_hep=[
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_01/hep_to_root.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_02/hep_to_root.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_03/hep_to_root.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_04/hep_to_root.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_05/hep_to_root.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_06/hep_to_root.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_07/hep_to_root.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_08/hep_to_root.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_09/hep_to_root.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_10/hep_to_root.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_11/hep_to_root.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_12/hep_to_root.root',
'/scratch/skulkarni/monophoton_backgrounds/MadGraph5_v1_5_14/Gamma_jet_pythia_cross_checks/Events/run_13/hep_to_root.root',
]

P8_hep=[
'/scratch/skulkarni/monophoton_backgrounds/pythia8_pp_gammaj/DATA_pp-gammaj_8TeV/BSMHiggs_hep_to_root.root'
]
